### ISSUE TITLE
ValueError: ctypes objects containing pointers cannot be pickled

### ISSUE THREAD

**Issue by lsiddiqsunny** [Kolkir/cppminer#5]
Can anyone find a solution for this?
```
Traceback (most recent call last):
  File "/Users/lsiddiqsunny/Documents/cppminer/src/miner.py", line 144, in <module>
    main()
  File "/Users/lsiddiqsunny/Documents/cppminer/src/miner.py", line 119, in main
    p.start()
  File "/Users/lsiddiqsunny/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/lsiddiqsunny/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/lsiddiqsunny/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/lsiddiqsunny/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/lsiddiqsunny/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/lsiddiqsunny/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/lsiddiqsunny/.pyenv/versions/3.9.4/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
ValueError: ctypes objects containing pointers cannot be pickled
```

**Comment by Kolkir** [comment]
Hello, I didn't see the application modules in the call stack. Only the miner.py that tries to launch a process and fails. Did you try to run app in a single process mode? Are there any problems in such a case?

**Comment by CyrilleFinet3** [comment]
Hello @lsiddiqsunny , I have the same problem, do you found a solution? Thanks
